language: python
python:
- '2.7'
- '3.5'
- '3.6'
install: pip install pyflakes==1.5.0
script: pyflakes beeline && python setup.py test
deploy:
  provider: pypi
  user: honeycomb
  on:
    tags: true
    repo: honeycombio/beeline-python
  password:
    secure: BstULKsJO1uJ3Q+wI1ox0St79sFiS7nzpOzrapdSpi4H/TBRI+yiyzL/vVrDKz0Xh42Krn3Ht9dpAR07VjneolTtkwL6ZFrrEiSyA9QVnJUqHQooBjJaEFpZN2gaffQ1y6bAXqI1jYm8OUxQRoKdpEQLudpJdGDuMju2bhUygfzKMl6VO0132w09oPresfcoRlalHgDhGVqYAu4SV7PvEfndvRGXyTiRjWuWbPkFOtFkSf3UsiF3spZf7Xskyfs4N2QR+FnfK62RMby0ZYkJ9yxXQkTOkJ4BR4zud01rPPue0opa1LhkPAoqWUJUyYNs+2r4kJwPHzb8yf1TJDNDpQs/PdOL7ss0MrRRl/k7Acg8kEqwxUhPNfRVlcNs4uOyuuhuGAMDtIRLQ11y4yYTW1aOMgbjUExJqMLixeoDQgjBN7LhY+HZrMYZLHCkI3IPha8gfKNWAqyuoLjWcFzWAAEWjYSNxE3ruaUxxhMsLPXfOmH6NZj+IIgVbFU85glYa3sbGAuEH5UCKYebRdzw2ZNyHhrGIqgmQyLZg6YHCw58rn//94F9EP0XR9sWkh2rlLDz8wy/ThUtTZPHhLzzvR2gmASalmOjfYfR4Kxrtz22UX2mp5da8eJdZy/cue1gh5kFQuW3q6LllqWLqn9CRNjlNoPzTLHPaAFGEoQ45oA=
after_deploy:
- ./push_docs.sh
env:
  global:
    secure: nbpODCk4rMJ4dDTd78MnCRwqFZfQixZLG1HjnOIHph8R/9MHds6MZzPdHcR2tWw2vjZmi7/2vcmqKx3RPmYVmn9jpg29Mosetjfk23KHtk7gham5mDTAhShtwLjZ+lPDvHkD7bEaPg74uJoPSbLS/BBHWgaEBH3Rx0LA96dlulsS/z8jRFDBG3tGqexTmcUvlHvODxZCKgm46xLOsdo5wy9LK+FwFol8/ACcClR9mRfyuHgr73LAIK6F6csj5kF4SoEzSezydgYrk9O22sCgudeoJLaJQn4OefKGsSR2bhJTmf8FvwEmdx2fQ9lA+9OcgboXQPoRGFEYpG88e14E7XXeylPNA2XSvVLmWJmgyioDw92/Kj6ddkV1lu3eE5QnJ7XDlLeBUNDUaxzZ8Enq5v7Dm1t6dYgBJ81NzQBTI99U/LLusYnWGgrclpuL+3qJqNoCPjrqUE1rGrphMrLi1V8hoba4XQXmuL9TWru/39xzy1RX5bej4KFIeqSIHQg2U6msDkf4KV86eYzwAi2K29T72mt4fSoMKfq6T1A1ELrAt7QXswaUG55gboVT8/aZXVjaop19gADOllWqDXwfebr5TrWWJriKhEEeSnmBHruJVOb/v1IGGjO6eocGyPbiUuFQOc1KsOwtna4I7nZtr0HvOY46fmIN1yLTRjo9Q1s=
